#Remove comments and rename the file to bootstrap.yml for using cloud config
#spring:
#  application:
  
# Name of the service that is using with Zuul routes to forward specific requests to this service  
#    name: accounts-webservice
#  cloud:
#    config:
      
# Define the URL from where this service would pick up it's external configuration. Note that it is
# pointing to the config-server aplication         
#      uri: http://localhost:8888


#server:
#  port: 8082
  
#spring:
#  data:
#    mongodb:
#      database: test
#      host: localhost
#      port: 27017

